name: Dylan Murphy
email: dylan@cotangent.space
description: > 
  I am a lecturer at the University of Arizona.
baseurl: ""
url: "http://mpdylan.github.io"
github_username: mpdylan

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
permalink: /blog/:year/:month/:day/:title
plugins: jekyll-include-cache
