name: Dylan Murphy
email: dylan@cotangent.space
description: > 
    Bayesian statistician in the sports industry.
baseurl: ""
url: "http://mpdylan.github.io"
github_username: mpdylan
mastodon_username: dylanm
mastodon_instance: mathstodon.xyz

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
permalink: /blog/:year/:month/:day/:title
plugins: jekyll-include-cache
