name: Dylan Murphy
email: dmurphy@math.arizona.edu
description: > 
  I am a Ph.D. candidate and lecturer at the University of Arizona.
baseurl: ""
url: "http://mpdylan.github.io"
github_username: mpdylan
mastodon_username: dylan
mastodon_instance: scholar.social

markdown: kramdown
permalink: /blog/:year/:month/:day/:title
