name: Dylan Murphy
email: dylan@cotangent.space
description: > 
  I am a lecturer at the University of Arizona.
baseurl: ""
url: "http://mpdylan.github.io"
github_username: mpdylan
mastodon_username: dylan
mastodon_instance: scholar.social

markdown: kramdown
remote_theme: poole/hyde
permalink: /blog/:year/:month/:day/:title
